services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: make test
  app-production:
    build:
      context: ./app
      dockerfile: Dockerfile.production
    image: gpiento/docker-project-74
    command: make test
