# docker-compose.yml
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make test

  app-production:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gpiento/docker-project-74
    command: make test
