# docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make test
    depends_on:
      - db

  app-production:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gpiento/docker-project-74
    command: make test

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: