# Dockerfile.production

FROM node:20.12.2
WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci
COPY app/. .
COPY /app/.env.example ./.env

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD [ "make prepare-env", "make start" ]
