# docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gpiento/docker-project-74
    command: make test
    environment:
      - DATABASE_HOST = ${DATABASE_HOST}
      - DATABASE_PORT = ${DATABASE_PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER = ${DATABASE_USERNAME}
      - POSTGRES_PASSWORD = ${DATABASE_PASSWORD}
      - POSTGRES_DB = ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: