services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make test
  app-production:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gpiento/docker-project-74:lastest
    command: make test
