name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Запускать только при push в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run tests
        run: make ci

      - name: Build production image
        run: docker-compose -f docker-compose.yml build app-production

      - name: Push production image to Docker Hub
        run: docker-compose -f docker-compose.yml push app-production
