name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=gpiento/docker-project-74
          cache-to: type=inline
          push: true
          tags: gpiento/docker-project-74

      - name: Check
        run: |
          make ansible-generate-env
          docker compose --file docker-compose.yml up --abort-on-container-exit
